### ISSUE TITLE
Using predicates for failure reasons

### ISSUE THREAD

**Issue by rzaharenkov** [palkan/action_policy#120]
I have a question about failure reasons. The application I am working on is the marketplace. I will try to describe it using the very simplified version of our domain model:
- Let's assume the we have candidates and we have jobs. 
- Candidate can apply to a job if both candidate and job are active.
- Let's assume that we have model `Candidate` that implements method `active?` and we also have a model `Job` that implements the method `active?` as well. 

The simplest implementation for the `JobPolicy` that comes to my mind:

```ruby
class JobPolicy < ApplicationPolicy
  authorize :candidate

  def apply?
    candidate.active? && record.active?
  end
end
```

It works just fine until we need to know the reason why some particular candidate could not apply to a job. I have looked into documentation and it seems like I have to turn every predicate into policy rule check in order to use reasons. 

Technically I can do something like:

```ruby
class JobPolicy < ApplicationPolicy
  authorize :candidate

  def active?
    record.active?
  end

  def apply?
    allowed_to?(:active?, candidate) && allowed_to?(:active?)
  end
end

class CandidatePolicy < ApplicationPolicy
  authorize :candidate

  def active?
    record.active?
  end
end
```

And it will work. I can even customize messages using I18n, e.g:

```yml
en:
  action_policy:
    policy:
      job:
        apply?: "You can't apply to this job"
        active?: "Job is not active"
      candiate:
        active?: "You profile is not activated yet"
```

Although I feel wrong to have authorization rules like `active?`. It's not an action that could be performed on the record, it's a property of the record and it seems weird to me to define method in the policy just in order to be able to describe a reason.

Is there any other way to implement the same behavior?

If I would design this API I would probably provide some DSL method that would allow to make the early return from the authorization rule and preserve the reason. E.g:

```ruby
class JobPolicy < ApplicationPolicy
  authorize :candidate

  def apply?
    deny!(:candidate_not_active) unless candidate.active?
    deny!(:job_not_active) unless record.active?
  end
end
```

```yml
en:
  action_policy:
    policy:
      job:
        apply?: 
          message: "You can't apply to this job"
          reasons:
            candidate_not_active: "You profile is not activated yet"
            job_not_active: "Job is not active"
```

I don't have strong opinions about either method name or implementation details. It could be implemented with exception (so if the check is failing it will break the method execution) or it could contribute to the result without instant failure. I'd probably prefer 1st option but I can also see a value in second approach.
